### ISSUE TITLE
Running with reverse proxy

### ISSUE THREAD

**Issue by krystalcode** [elastic/kibana-docker#138]
I used to be able to run Kibana behind a reverse proxy (`jwilder/nginx-proxy`). Trying out the latest release (`6.7.1`) and I can't make it work.

The proxy listens to port `80` but it knows that Kibana listens to `5601` and forwards the requests there. I use a domain, say, `http://kibana.apps.localhost`. I have tried the following settings:

* server.name: kibana.apps.localhost
* server.host: kibana.apps.localhost
* server.rewriteBasePath: true
* server.basePath: kibana.apps.localhost

I keep getting a 504 timeout which implies that the request is forwarded by Nginx but there is no response by Kibana. No logs printed by Kibana.

Any ideas?

**Comment by jbudz** [comment]
Hey @krystalcode sorry for the delay on a response here - we're moving the contents of this repo over to elastic/kibana and if you're still looking into this https://discuss.elastic.co/kibana is probably the quickest way to get a response.

On first glance, no need for rewriteBasePath or server.basePath - you would want those if you wanted to server those under a subdirectory.  e.g. localhost/foo would be server.basePath: /foo.

server.name is for identification purpose so that shouldn't have an impact.

server.host depends on what your hosts file looks and if docker is port forwarding.  If not you'll likely need to bind kibana via a public address (0.0.0.0).  Any luck with that - keep in mind that is public?

We'll be archiving this repo eventually, so I'm going to close this out for now but feel free to ping me here in the meantime or on discuss (@jbudz)
