### ISSUE TITLE
Kibana docker image doesn't connect to elasticsearch docker image

### ISSUE THREAD

**Issue by PT-73** [elastic/kibana-docker#17]
There are no specific instructions on how to setup kibana to connect, based on the elasticsearch docker image default settings
es ran fine with the default docker run command: 
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1” docker.elastic.co/elasticsearch/elasticsearch:5.2.2

kibana fails with this command:
docker run -e "elasticsearch.url=http://localhost:9200" -e "elasticsearch.password=changeme" -e "elasticsearch.username=elastic" docker.elastic.co/kibana/kibana:5.2.2

trying with this command
docker run -e "ELASTICSEARCH_URL=http://localhost:9200" -e "ELASTICSEARCH_PASSWORD=changeme" -e "ELASTICSEARCH_USERNAME=elastic" docker.elastic.co/elasticsearch/elasticsearch:5.2.2

**Comment by jarpy** [comment]
The Kibana container cannot refer to the Elasticsearch container as `localhost`. When you are in the Kibana container, `localhost` _is_ the Kibana container.

I'm not sure what your intent is, but given that you are binding Elasticsearch to port 9200 on the host system, I'll assume that you'd like the processes to appear like traditional, non-containerized ones and not take advantage of [Docker Networking](https://docs.docker.com/engine/userguide/networking/).

If that's so, then you could bind Kibana directly to the host NIC like this:

```
docker run --net=host -e "ELASTICSEARCH_URL=http://localhost:9200" docker.elastic.co/kibana/kibana:5.2.2
```

With `--net=host`, `localhost` will actually mean the host system, since it and the Kibana container now exist on the same NIC/network namespace.

**Comment by jarpy** [comment]
See also: https://discuss.elastic.co/t/kibana-docker-image-doesnt-connect-to-elasticsearch-image/79511/4
