### ISSUE TITLE
Test for missing Environment Variables

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/kibana-docker#26]
Is there some way we can fail a test if we're missing a Kibana yml setting as environment variable?   For example, `SERVER_DEFAULTROUTE` ( `server.defaultRoute`) does not appear to be supported.

**Comment by Kikketer** [comment]
There seems to be quite a few missing variables.  One that's critical to my team is `SERVER_DEFAULTROUTE`.  It's not currently available/working as an environment variable but does work as a yml config: server.defaultroute

**Comment by jakommo** [comment]
IIRC @jarpy or @dliappis mentioned that they plan to redo the way how environment variables are exposed, so it would not require a white list.

**Comment by jarpy** [comment]
`server.defaultRoute` was added in a couple of weeks ago. Which images version are you having trouble with? Have you pulled the latest updates?

**Comment by jarpy** [comment]
We will definitely have a long-term solution to the environment variable problem, no later than 6.0.

The hardest part is choosing a format that works for all products and meets all these requirements:

---

###### Kubernetes and Bash do not support dots in names
We'll probably just translate underscores to dots. But does/will any of our products have _actual_ underscores in a config option? If they do, then translating them to dots will break something.

###### Case-mangling requires "blessed" variables for Kibana
Environment variables are traditionally in all-caps. However, Kibana uses mixed-case names for configuration items, so in the context of Kibana, case-mangling actually destroys information. We can't programmatically map `SERVER.DEFAULTROUTE` to `server.defaultRoute` without capturing the extra information in advance. This is what led to the blessed variable whitelist and the inevitable problems associated with it. Double-declaration is a terrible thing to do, I freely admit!

I would love it if Kibana could accept `--server.defaultroute` instead.

###### The environment is a shared namespace
We can't map _every_ environment variable to process options. Some of the variables that are set will be "foreign", like `$PATH`, `$HOME`, and `$TERM`.

We might have to namespace all our variables like: `kibana.server.defaultRoute`.

---

As far as I can see, currently, the only format that would work for all cases is this:

`es_default_path_data`
`kibana_maxPayloadBytes`
`ls_pipeline_workers`

It looks pretty ugly, but I'm not sure we have much choice. I'm very interested in your thought and feelings, @dliappis

**Comment by jarpy** [comment]
To answer the initial question about testing, I think the only thing that would work is to generate the blessed variable list from the Kibana source code or documentation. That's quite tricky, and is made even more so by the fact that X-Pack introduces additional options.

I don't think there's any value in writing explicit tests for the individual variables, since, if you know/remember to write the test, then you know to add support for the option. The biggest source of error is the image (and its maintainer) not being aware of changing options in Kibana.

**Comment by dliappis** [comment]
> As far as I can see, currently, the only format that would work for all cases is this:
> 
> es_default_path_data

@jarpy It occurred to me that es already accepts the parameter `ES_JAVA_OPTS` to override jvm options like the default heap size, so, (regardless of the capitalization) the wrapper needs to treat this env var as an exception. I  am going discuss with @jasontedor tomorrow, whether there are other exceptions we need to be aware of and the best way to mitigate this -- as we all know that exceptions usually create problems in the long run.

For the `kb_` and `ls_` prefix I am perfectly happy, however, let's wait one more day to finalize the alternative env var definition scheme for ES so that we are consistent with the capitalization across all images.

**Comment by lruslan** [comment]
+1 for improving handling of environment variables, I'd like to enable 'elasticsearch.logQueries: true', and now it looks only option is to build own image

**Comment by jarpy** [comment]
There certainly is room for improvement with environment variable configuration. However, building a custom image is not the only alternative.

There's a third option, which is the one which we recommend for most circumstances, and that's [bind-mounted configuration](https://www.elastic.co/guide/en/kibana/6.2/_configuring_kibana_on_docker.html#docker-bind-mount-config). Because Kibana uses a YAML based configuration file, the resulting config can be quite a complex data structure. It's genuinely hard to represent such a data structure with a system of environment variables.

**Comment by jbudz** [comment]
As jarpy mentioned, probably the most consistent for now is to bind mount kibana.yml.  Going forward we'll be look into automating the whitelist, and later possibly adopting elasticsearch's approach.

We're migrating issues to the kibana repo and are tracking this at https://github.com/elastic/kibana/issues/30598.
