### ISSUE TITLE
Missing xpack.apm.ui.enabled in kibana_vars

### ISSUE THREAD

**Issue by tvernum** [elastic/kibana-docker#77]
Documented here: https://www.elastic.co/guide/en/kibana/6.2/apm-settings-kb.html
The current kibana_vars white list has `xpack.apm.enabled` but not `xpack.apm.ui.enabled`

**Comment by tylersmalley** [comment]
@sqren, should the documentation be updated to reflect using `xpack.apm.enabled`?

**Comment by sqren** [comment]
Are we talking about two different things?

`xpack.apm.enabled`
It is an xpack-wide feature that users can disable a plugin via `xpack.<plugin-name>.enabled`. If other plugins document this we should too.

`xpack.apm.ui.enabled`
This was a hack [requested by cloud](https://github.com/elastic/cloud/issues/9531#event-1375773318). We [considered adding it to the whitelist](https://github.com/elastic/kibana-docker/pull/72) but decided against it. It is my understanding that we can remove this setting in 6.4 since APM will be officially supported on Cloud at this time.
(although people might still want to hide APM in the menu - I honestly don't know)

**Comment by tvernum** [comment]
Well the docs and the whitelist are not on sync.

The docs describe `apm.ui.enabled` but not `apm.enabled`. The whitelist is the opposite.
That's a pretty terrible experience for docker users.

I have no opinion on which option(s) should be recommended to users, but let's at least be consistent.

**Comment by sqren** [comment]
Again, I think it makes sense to document `xpack.apm.enabled` so it matches the whitelist.
I'm not really sure what the future is for `xpack.apm.ui.enabled`. If we want to keep it, it should be added to the whitelist, if not it should be removed from the docs. That would bring consistency, right?

@joegallo Is `xpack.apm.ui.enabled` still needed by cloud to hide the APM menu item?

**Comment by joegallo** [comment]
> @joegallo Is xpack.apm.ui.enabled still needed by cloud to hide the APM menu item?

Yes.

**Comment by sqren** [comment]
@joegallo Okay, thanks!
