### ISSUE TITLE
Missing server.rewriteBasePath in kibana_vars

### ISSUE THREAD

**Issue by tsullivan** [elastic/kibana-docker#89]
In 6.3.x, when we have a `SERVER_BASEPATH` setting, Kibana will log this:
```
"message":"You should set server.basePath along with server.rewriteBasePath. Starting in 7.0, Kibana will expect that all requests start with server.basePath rather than expecting you to rewrite the requests in your reverse proxy. Set server.rewriteBasePath to false to preserve the current behavior and silence this warning."
```

It suggest that I should have a `SERVER_REWRITEBASEPATH` setting, but that doesn't work, because it isn't a whitelisted setting.

**Comment by jojoob** [comment]
I came across this issue when I used the Kibana docker image docker.elastic.co/kibana/kibana:6.4.0. The bug is fixed in this repo but since the offical image was not rebuild. Is there a fixed cycle for rebuilding the official images? I know I can build the image myself... But just want to know about a release cycle for the elastic docker images in general.

**Comment by jojoob** [comment]
Thank you for the clarification!

Okey, so that means new docker images are not released independently of new elastic (elasticsearch/kibana/...) releases. Therefore, bugs within this repository will never ported back to existing elastic version.

**Comment by jarpy** [comment]
You’re welcome, and that’s correct. Elastic considers the images to be
simply another part of the released version, and bug fixes demand a new
version number.
