### ISSUE TITLE
Docker Kibana 6.3.2 loading issues

### ISSUE THREAD

**Issue by kkr78** [elastic/kibana-docker#91]
1) The Custom Docker image that built using the following files, is taking a long time to initialize the container. 

Docker File

FROM docker.elastic.co/kibana/kibana:6.3.2
ADD kibana.yml /usr/share/kibana/config/

kibana.yml

xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false
elasticsearch.url : ${ELASTICSEARCH_URL}
elasticsearch.requestTimeout: 10000

server.host: "localhost"
server.port: 5601

docker run -p 5601:5601 -e ELASTICSEARCH_URL=http://xxx.search.xxx.com/kibana-docker:latest

Logs

{"type":"log","@timestamp":"2018-07-26T22:56:22Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for stateSessionStorageRedirect, status_page, timelion, dashboardViewer, apm and kibana. This may take a few minutes"}

{"type":"log","@timestamp":"2018-07-26T22:59:13Z","tags":["info","optimize"],"pid":1,"message":"Optimization of bundles for stateSessionStorageRedirect, status_page, timelion, dashboardViewer, apm and kibana complete in 170.94 seconds"}

2) If I run the image "docker.elastic.co/kibana/kibana:6.3.2" directly then it loads faster. 

docker run -p 5601:5601 -e ELASTICSEARCH_URL=http://xxx.search.xxx.com docker.elastic.co/kibana/kibana:6.3.2

{"type":"log","@timestamp":"2018-07-27T02:46:59Z","tags":["status","plugin:kibana@6.3.2","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-07-27T02:46:59Z","tags":["status","plugin:elasticsearch@6.3.2","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}

3) If I pass additional environment argument to disable monitoring then again it takes lon time to initialize

docker run -p 5601:5601 -e ELASTICSEARCH_URL=http://xxx.search.xxx.com -e XPACK_MONITORING_ENABLED=false docker.elastic.co/kibana/kibana:6.3.2

{"type":"log","@timestamp":"2018-07-27T02:51:18Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, login, logout, dashboardViewer, apm and kibana. This may take a few minutes"}
{"type":"log","@timestamp":"2018-07-27T02:54:46Z","tags":["info","optimize"],"pid":1,"message":"Optimization of bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, login, logout, dashboardViewer, apm and kibana complete in 207.35 seconds"}
 
why it's taking more than 3 mins to load? why there is such a big difference?

**Comment by tylersmalley** [comment]
It needs to reoptimize due to disabling the plugins.  Are you using any of the X-Pack features? If not, it looks like you might benefit from using the OSS image.

**Comment by kkr78** [comment]
I just need monitoring feature in the xpack. From 6.3, that feature is free. Where can I download image with Open Source license?

**Comment by xeraa** [comment]
You can find all our images on https://www.docker.elastic.co and the open source Kibana image is `docker.elastic.co/kibana/kibana-oss:6.3.2`. However, even just for monitoring you will need `docker.elastic.co/kibana/kibana:6.3.2` — monitoring is free, but not open source.

**Comment by kkr78** [comment]
Thanks for pointing out to the right images. I was able to deploy both open source version of elastic and Kibana successfully. I would like to take advantage of some of the free features from Xpack without forcing the container to reoptimize. any ideas how can I build a custom image with oss and free features of Xpack?

**Comment by xeraa** [comment]
1. I don't think this is easily possible and it's probably against the [license agreement](https://www.elastic.co/eula) — while basic is free for you to use, it's not open source and there are certain limitations.

2. If you apply your settings through environment variables instead of baking in a custom kibana.yml, you shouldn't run into the optimization phase.

3. Once you build your custom image it will be stored locally. So even if you upgrade to every patch level release you'll only have to rebuild it every few weeks — is that optimization phase such a big problem then? If you have multiple people who need that image it would make sense to run your own docker registry where you can push your custom image and then you'd only have to build an optimize it once.

**Comment by kkr78** [comment]
I m deploying these images to AWS ECS containers. I found a couple of issues with it, 1) ELB is restarting the instance if the container doesn't respond within a min. The overall reoptimize takes around 3 mins so I have to adjust parameters to support reoptimize and those settings not optimal after the reoptimize. 2) Nature of ECS, it might scale or up down or spin up on different instances depending on the deployments and availability of the resources. Also, developers might spin up instances locally. Docker images published to ECS registry. I tried to build the custom images using the Docker file provided but that didn't help. May I know, how I can build a custom image with optimization? The goal is to avoid optimization at runtime.

**Comment by xeraa** [comment]
The optimize step only happens when you change something in the image, so if you push the final image you shouldn't run into it.

Just to be sure: You are logged into your registry, you tag the the image you've created with the Dockerfile above and you push that tag, so it's being used afterwards?

PS: There was a bug around optimizations, but it has been fixed in 6.1.2 and 6.2.0: https://github.com/elastic/kibana/pull/15910

**Comment by kkr78** [comment]
I observed it's optimizing at runtime with the custom image (built using the Docker and kibana.yml mentioned in the first step), locally and on ECS. 

1) local
docker run -p 5601:5601 -e ELASTICSEARCH_URL=http://xxx.search.xxx.com/kibana-docker:latest

2) published to ECS registry and run the task
docker tag kibana-docker:latest xxx.dkr.ecr.us-east-1.amazonaws.com/kibana-docker:latest
docker push xxx.dkr.ecr.us-east-1.amazonaws.com/kibana-docker:latest

**Comment by jarpy** [comment]
There's a trick you can use to trigger an optimisation step when building a custom image. Maybe it will be of some help in your situation.

https://github.com/elastic/kibana/issues/6057#issuecomment-403789147

**Comment by jbudz** [comment]
Kibana supports a standalone optimization flag now, bin/kibana --optimize that can  be baked into an image build.

We're migrating issues over to the elastic/kibana repo, but this issue is fairly stale so I'm going to close it out for now.  Going forward feel free to reopen in the kibana repository.
