### ISSUE TITLE
kibana docker image

### ISSUE THREAD

**Issue by android-LPJ** [elastic/kibana-docker#98]
default confighas a issue.
We need to change conf/kibana.yml.

default:
docker.elastic.co/kibana/kibana:6.4.0
bash-4.2$ cat config/kibana.yml 
server.name: kibana
server.host: "0:5601"
elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true

need change to:
server.name: kibana
elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true

**Comment by jarpy** [comment]
The [default for this image](https://github.com/elastic/kibana-docker/blob/3b6afcca8f709c326e4dcdca26afe6036c73e8b7/build/kibana/config/kibana-oss.yml#L5) actually sets `server.host` to simply `"0"` so that Kibana listens on all interfaces. This enables other containers in the same network, and the host system, to access Kibana.

Here is the file in the image:
```
$ docker run --rm -it docker.elastic.co/kibana/kibana:6.4.0 cat config/kibana.yml
---
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
```

If you are seeing `"0:5601"` for `server.host`, then something, or someone, has modified the image you are using.

**Comment by android-LPJ** [comment]
thank you @jarpy
